### ISSUE TITLE
Touch pad click for lefty

### ISSUE THREAD

**Issue by rubaboo** [AppGround-io/bluetooth-keyboard-and-mouse-support#108]
**Is your feature request related to a problem? Please describe.**
When mouse buttons are swapped on a PC, pad click produces a right click.

**Describe the solution you'd like**
Pad click should always produce "primary button" click, not "context" click.

**Comment by AppGround-io** [comment]
The app already sends the primary button (ID 1) when you click with one finger and the secondary button (ID 2) when pressing with two fingers. 

If I understand the problem right, it seems that you changed the behavior on the PC. Now the button with ID 2 is the primary button and the button with ID 1 is the secondary button.

Since the app does not know that you changed the behavior on the PC, the only thing you can do is to change it back on the PC.
