### ISSUE TITLE
Is FireOS 7 or are FireHD 2019/2020 models compatible?

### ISSUE THREAD

**Issue by WalkingDot** [AppGround-io/bluetooth-keyboard-and-mouse-support#67]
Is it known if Amazon FireHD tablets are compatible with the app?
The latest models with FireOS 7 are based on Android 9.

I haven't used a FireHD yet, but recently the 8" tab was offered for less than 60€ and the 10" for less than 90€. For that price I would buy such a tab just for the app :)

**Comment by AppGround-io** [comment]
The tablet unfortunately only supports the compatibility mode connection mode and not the normal connection mode. 
This is a problem with many cheaper devices even if they have Android 9.
The app still works, but connections can be tricky to setup and reconnection is a problem as well. Amazon can still support the normal mode with an update, but I would not bet on it.

**Comment by WalkingDot** [comment]
Thank you for your help. Than I try maybe the upcoming model :)

**Comment by OSH1980** [comment]
WalkingDot, sorry for this comment. But you are my last hope, really and I can't contact with you otherwise. I created this asccount on GitHub, but I'm not a programmer. I saw, you are involved in 3dfx-QEMU. I have problem to run 3dfx under QEMU on Ubuntu 20.04. What I did:
1. I compiled QEMU with kjliew's patch.
2. I compiled OpenGlide with kjliew's patch and install linglide2x.so in /usr/local/lib
3. I installed Windows 98 SE, copied glide 2x.dll into a directory, then copied test04.exe into the same directory to check if Glide works. But it doesn't. 
4. I have no idea what's now, nobody wants to help me. Neither kjliew nor Askmewho from this topic: https://github.com/kjliew/qemu-3dfx/issues/1 wants help me. And I saw - you did this trick. I'm really frustrated.
