### ISSUE TITLE
Pressing Shift key or Backspace on a hardware keyboard results in 'endless delete' within 

### ISSUE THREAD

**Issue by alexanderadam** [AppGround-io/bluetooth-keyboard-and-mouse-support#92]
**Describe the bug**

I'm using a tablet (Galaxy Tab S6) with keyboard cover together with `io.appground.blekpremium` 2.22.0 (30-19). Every time I want to write uppercase though (or just press the Shift key), the app seem to send the signal to delete characters endlessly. I have to switch to soft keyboard again to continue writing. This also happened with Galaxy Tab S4 and keyboard cover, so it's not specific to this model.
Everything is working in other apps.

**To Reproduce**
1. Use hardware keyboard
2. Write something and press Shift key

**Expected behavior**

Shift key should not lead to deleted characters

**Comment by SuperMarioSF** [comment]
Hi.
I have encountered the same bug, but slightly different. My problem is on Alt key.
I'm using a phone with a hardware keyboard, more specificly, Unihertz Titan. 

I connected my phone to my Linux laptop, and run `xev` to inspect for problem.
Normal character key works fine. Even Shift key is fine.
The problem is Alt Key.

`xev` output is:
```
KeyPress event, serial 36, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197100182, (74,55), root:(2865,482),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
--
KeyPress event, serial 36, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197100183, (74,55), root:(2865,482),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
--
KeyRelease event, serial 36, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197100204, (74,55), root:(2865,482),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
```
As you can see, key `ALT_L` never released. This also caused Backspace key being treated as `Esc` key (Alt+Backspace). On my other android device (and this PC running `xev`), this behavior caused backspace key being treated as navigation back key.

My device has only one Alt key (for symbol and number input), sending both Alt_L and Alt_R seems not right.
If possible, can you add an option to not send Alt key code to target device altogether? This could fix this problem.

About the backspace problem. It seems only appears after a long press on backspace. Once long press backspace primed, the only way to stop this is press any character key. But if somehow a function key is also in a incorrect state (for example, the broken Alt key talked above), press key which can cause incorrect state also resumes endless backspace...

Here is some extra test about non-stop backspace problem:
```
############################ ALT PRESSED ############################
KeyPress event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197616656, (122,141), root:(3490,446),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
######################### BACKSPACE PRESSED #########################
KeyPress event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197616656, (122,141), root:(3490,446),
    state 0x8, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyPress event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197616656, (122,141), root:(3490,446),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
--
KeyRelease event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197616933, (122,141), root:(3490,446),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
--
KeyRelease event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197616978, (122,141), root:(3490,446),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
--
KeyRelease event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197617317, (122,141), root:(3490,446),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyPress event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197617317, (122,141), root:(3490,446),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
######################## BACKSPACE RELEASED ########################
KeyRelease event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197617357, (122,141), root:(3490,446),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyPress event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197617357, (122,141), root:(3490,446),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyRelease event, serial 50, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197617397, (122,141), root:(3490,446),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--

........ Omitted duplicates ........
--
KeyPress event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774700, (57,110), root:(3425,415),
    state 0x8, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyRelease event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774740, (57,110), root:(3425,415),
    state 0x8, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyPress event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774740, (57,110), root:(3425,415),
    state 0x8, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,

####################### CHARACTER W PRESSED #######################
--  
KeyRelease event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774756, (57,110), root:(3425,415),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
--
KeyRelease event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774756, (57,110), root:(3425,415),
    state 0x0, keycode 22 (keysym 0xff08, BackSpace), same_screen YES,
--
KeyPress event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774757, (57,110), root:(3425,415),
    state 0x0, keycode 25 (keysym 0x77, w), same_screen YES,
--
##################### CHARACTER W RELEASED ####################
KeyRelease event, serial 52, synthetic NO, window 0x4600001,
    root 0x309, subw 0x0, time 197774758, (57,110), root:(3425,415),
    state 0x0, keycode 25 (keysym 0x77, w), same_screen YES,

```

**Comment by AppGround-io** [comment]
Thank you for the reports. 

The new version 3.0.1 has multiple bug fixes for the keyboard. Please let me know if this version fixes your problems.

**Comment by SuperMarioSF** [comment]
> Thank you for the reports.
> 
> The new version 3.0.1 has multiple bug fixes for the keyboard. Please let me know if this version fixes your problems.

Hi, it's works fine now. I'm using v5.0.2 from beta channel at google play store.

However there still a minor usability issue with Windows (or major of Linux Desktops) machine, which caused by sending Alt key event. This keyboard (and many more shrinked phone hardware keyboard implemention) use Alt key to type numbers ans symbols. This will cause lost focus on window (since Alt key will focus on menu bar) when typing number and symbols. Maybe it's necessary to add an option to disable certain key code to prevent this problem happen. Btw Android works just fine because Android didn't care about much about Alt key.

(This seems to be an improvement rather than a bug report now. Do I need to open a new issue about this?)

**Comment by alexanderadam** [comment]
> The new version 3.0.1 has multiple bug fixes for the keyboard. Please let me know if this version fixes your problems.

I totally forgot about this. It is working since this version.
Thank you! :+1:
